plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rinoize.rigear'
    compileSdk 35

    defaultConfig {
        applicationId "com.rinoize.rigear"
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName "0.5.0"

        ndk {
            abiFilters 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
                targets 'rigear_jni'
                arguments '-Dgearmulator_BUILD_JUCEPLUGIN=OFF',
                          '-Dgearmulator_SYNTH_OSIRUS=ON',
                          '-Dgearmulator_SYNTH_OSTIRUS=OFF',
                          '-Dgearmulator_SYNTH_VAVRA=OFF',
                          '-Dgearmulator_SYNTH_XENIA=OFF',
                          '-Dgearmulator_SYNTH_NODALRED2X=OFF',
                          '-Dgearmulator_SYNTH_JE8086=OFF',
                          '-Dgearmulator_SYNTH_88EMU=OFF',
                          '-Dgearmulator_COMPONENT_DSPBRIDGE=OFF',
                          '-DBUILD_TESTING=OFF',
                          '-DANDROID_ARM_NEON=TRUE',
                          '-DANDROID_STL=c++_shared'
            }
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path file('../../../../CMakeLists.txt')
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
